### ISSUE TITLE
(noob) question about initializing

### ISSUE THREAD

**Issue by chocolata** [johnRivs/wunderlist#2]
Hi John

I've been testing out your wunderlist api wrapper, but I'm already stuck... :-)
I'm not using any framework as suggested in your documentation.
My folder structure looks like this:

```
httpdocs
  includes
    wunderlist
       Wunderlist.php
       Authorization.php
       ...
  index.php
```

Now, in my index.php, I am trying to include the files. I was looking for an autoload.php file, but this does not seem to be included. I thus guessed the right file to include was Wunderlist.php. Please note that in my code, I have included the right clientID, clientSecret and accessToken.

```
<?php
require_once __DIR__.'/includes/wunderlist/Wunderlist.php';

use JohnRivs\Wunderlist\Wunderlist;

$clientId     = 'xxx';
$clientSecret = 'xxx';
$accessToken  = 'xxx';

$w = new Wunderlist($clientId, $clientSecret, $accessToken);

$w->getCurrentUser();
?>
```

If I try this, I get the error message:

`Fatal error: Trait 'JohnRivs\Wunderlist\Authorization' not found in /var/www/vhosts/mydomain.be/subdomains/planning/httpdocs/includes/wunderlist/Wunderlist.php on line 8`

This is probably a trivial question, but could you possible get me going? It'd be a great help.

**Comment by johnRivs** [comment]
Here's the thing. If you happened to use an autoloader, composer's autoloader for example, it would require every file in the directory. 

In your case though, you're only requiring 1 file. This package assumes it's gonna be installed with composer, so Wunderlist.php does not require the rest of the files. The error you see makes sense, because no other file than Wunderlist.php seems to be required.

Either use composer or require all the files in the directory (Wunderlist.php, Authorization.php...).

**Comment by chocolata** [comment]
Thanks a bunch! The only thing is now I'm bumping into the next error...

`Fatal error: Class 'GuzzleHttp\Client' not found in /var/www/vhosts/domain.be/subdomains/planning/httpdocs/includes/wunderlist/Wunderlist.php on line 123`

Is there a dependency on a third party script? Where can I find it if so? 

Thanks again.

**Comment by johnRivs** [comment]
You nailed it. This package relies on a well known HTTP client called [Guzzle](http://docs.guzzlephp.org/en/5.3/) to fetch data from the Wunderlist API.

Again, this package is meant to be installed with [composer](https://getcomposer.org/), which would also install the [dependency](https://github.com/johnRivs/wunderlist/blob/master/composer.json#L12).

**Comment by chocolata** [comment]
Hi John, thanks for letting me know. I'm just gonna get into Composer, I think. It's due time :-) Thanks for pushing me in the right direction!
