### ISSUE TITLE
Not able to create task

### ISSUE THREAD

**Issue by manishwy** [johnRivs/wunderlist#3]
Hi John

I am using your wunderlist api wrapper for one of my projects using kohana framework but have got stuck at creating task.

Guzzle is throwing this error: `[status code] 400 [reason phrase] Bad Request`

My create task method is something like this:
```php
public function create_task ($access_token, $task_params) {
    $attributes = array (
        'list_id' => $task_params['list'], 
        'title'   => $task_params['title']
    );

    $this->wunderlist = new Wunderlist(OAUTH_WUNDERLIST_CLIENT_ID, OAUTH_WUNDERLIST_CLIENT_SECRET, $access_token);
    
    return $this->wunderlist->call('POST', 'tasks',  $attributes);
}
```
I have modified the call method a bit as guzzle was not creating the request properly. It looks like this now:
```php
public function call($httpMethod, $endpoint, array $parameters = []) { 
    $parameters = array_merge([
        'headers' => $this->getHeaders(),
    ], [
        'body' => $parameters
    ]);

    $request = $this->http->createRequest($httpMethod, $this->baseUrl . $endpoint, $parameters);

    $response = $this->http->send($request);
}
```

I tried using the createTask method provided but still got the same response. Any ideas ?

**Comment by johnRivs** [comment]
The `body` key should be `json`. That fixes Guzzle's `Bad request` error for me.

**Comment by manishwy** [comment]
Thanks for the quick reply John. I have tried that also.

public function call($httpMethod, $endpoint, array $parameters = []) { 
    $parameters = array_merge([
        'headers' => $this->getHeaders(),
    ], [
        'body' => ['json' => $parameters]
    ]);

Still getting same error.

**Comment by johnRivs** [comment]
Replace `body` with `json`. The key, not the value.

**Comment by manishwy** [comment]
Oh my bad. Done. But still same error :|

```php
public function call($httpMethod, $endpoint, array $parameters = []) {
$parameters = array_merge([
'headers' => $this->getHeaders(),
], 
['json' => $parameters]);
```

**Comment by johnRivs** [comment]
I did a clean install and it's working just fine. What you're doing in the last comment is exactly what this package already does behind the scenes.

As you can see, the headers are being merged with the parameters that the `createTask` method accepts.
```php
public function createTask(array $attributes = [])
{
    $this->requires(['list_id', 'title'], $attributes);

    return $this->call('POST', 'tasks', ['json' => $attributes]);
}
```
```php
public function call($httpMethod, $endpoint, array $parameters = [])
{
    $parameters = array_merge($parameters, [
        'headers' => $this->getHeaders(),
    ]);
```

If you've changed something else, I'd have a look at that instead.

**Comment by manishwy** [comment]
So I looked into it a bit more. This is the request that is being created:

POST /api/v1/tasks HTTP/1.1 Host: a.wunderlist.com X-Client-ID: ************ X-Access-Token: ************************************************************* Content-Type: application/json User-Agent: Guzzle/5.3.0 curl/7.29.0 PHP/5.6.14 {"list_id":"280215260","title":"akjsnakjs"}

This is the detailed error response which I get on printing $e->getResponse() :

HTTP/1.1 400 Bad Request Cache-Control: max-age=0, private, must-revalidate Content-Type: application/json Date: Tue, 13 Dec 2016 17:12:51 GMT Server: nginx X-Current-User-ID: 33060343 X-Request-ID: af637370-c939-4bc0-9c79-2e3ee4fdf5ac-9171 Content-Length: 137 Connection: keep-alive {"error":{"type":"missing_parameter","translation_key":"api_error_missing_params","message":"Missing parameter.","list_id":["required"]}}

So it is sending list_id but wunderlist api is not receiving it.

**Comment by manishwy** [comment]
Ok I am going to do a clean install again and follow the package instructions step by step. Hopefully everything will work.

**Comment by johnRivs** [comment]
Do a `die(var_dump($parameters));` before the request is made, and see what exactly is being sent.

Also, remember to check the response. Wunderlist should return the task that was just created.

**Comment by manishwy** [comment]
die(var_dump($parameters)) is giving this:

array(2) { ["headers"]=> array(3) { ["X-Client-ID"]=> string(20) "**************" ["X-Access-Token"]=> string(60) "*************************" ["Content-Type"]=> string(16) "application/json" } ["json"]=> array(2) { ["list_id"]=> string(9) "280215260" ["title"]=> string(9) "akjsnakjs" } }

**Comment by johnRivs** [comment]
Are you sending `list_id` as a string? Try as an integer.

**Comment by manishwy** [comment]
Yep that did it. My bad should have checked the wunderlist api properly. Thanks a lot :)

**Comment by johnRivs** [comment]
No problem, glad I could help.

One day I'll finish the package and I'll make it so IDs are casted to integers, in case you want to pass them as strings. In the meantime, check out the [wiki](https://github.com/johnRivs/wunderlist/wiki) for method signatures.
